# Generated by Django 4.0.3 on 2022-03-11 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_userprofile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=250)),
                ('level', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('assigned_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.userprofile')),
            ],
        ),
    ]
