# Generated by Django 4.0.3 on 2022-03-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='author',
        ),
        migrations.RemoveField(
            model_name='student',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='student',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
